import {openSkills,readSkillFiles} from './design-skills.js';
import {attachPromptHints} from './prompt-hints.js';
import {escapeHtml as esc,fonts} from './model.mjs';
const icons={blank:'<path d="M17 8h19l12 12v36H17z M36 8v13h12"/>',mobile:'<rect x="20" y="5" width="27" height="54" rx="6"/><path d="M27 15h13M27 25h13M27 33h8M30 51h7"/>',slides:'<rect x="7" y="16" width="50" height="35" rx="4"/><path d="M15 25h17M15 33h12M15 41h20"/><rect x="40" y="24" width="10" height="15" rx="2"/>',document:'<path d="M16 7h23l11 12v38H16z M39 7v13h11M23 29h20M23 37h16M23 45h20"/>',wireframe:'<rect x="7" y="11" width="50" height="44" rx="4"/><path d="M7 21h50M14 27h35v16H14zM14 27l35 16M14 43l35-16M14 48h16"/>',animation:'<rect x="7" y="9" width="50" height="36" rx="6"/><path d="m27 19 13 8-13 8zM9 55h46"/><circle cx="25" cy="55" r="4"/>',ui:'<rect x="14" y="10" width="42" height="34" rx="4"/><rect x="7" y="22" width="42" height="34" rx="4"/><path d="M15 31h24M15 39h15M15 47h10"/>',cube:'<path d="m32 6 24 13v27L32 59 8 46V19zM8 19l24 14 24-14M32 33v26"/>',research:'<path d="M12 6h25l11 11v39H12zM21 26h14M21 35h12M21 44h9"/><circle cx="43" cy="42" r="10"/><path d="m50 49 8 8"/>',email:'<rect x="10" y="8" width="44" height="49" rx="5"/><path d="M18 20h29M18 29h29M18 38h21M18 47h15"/>',palette:'<rect x="7" y="10" width="50" height="47" rx="5"/><path d="m16 35 8-18 8 18M19 29h10M37 24h11M42 24v11"/><path d="M15 47h8M28 47h8M41 47h8" stroke-width="7"/>',diagram:'<rect x="22" y="5" width="21" height="12" rx="3"/><rect x="3" y="45" width="21" height="12" rx="3"/><rect x="40" y="45" width="21" height="12" rx="3"/><path d="M32 17v14H13v14M32 31h19v14"/>',flier:'<rect x="16" y="5" width="33" height="54" rx="3"/><path d="M22 13h20M22 44h20M22 51h13"/><path d="M22 21h20v16H22zM22 37l9-9 11 9"/>'};
export const templateIcon=key=>`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[key]||icons.blank}</svg>`;
export function createHome({api,openDocument,flush,generate,uploadFiles,commit,getDoc,dialog,toast}){
 const $=s=>document.querySelector(s);let library=null,chosen='blank',filter='projects',files=[],skills=[],skillsInitialized=false,skillsEdited=false,systems;
 try{systems=JSON.parse(localStorage.getItem('cosmic-design-systems')||'null');}catch{}
 if(!Array.isArray(systems))systems=[{id:'quiet',name:'Quiet editorial',background:'#f6f4ef',ink:'#244c41',accent:'#738d7d',font:'serif'}];
 $('#home-skills').onclick=()=>openSkills({getSkills:()=>skills,setSkills:next=>{skills=next;skillsEdited=true;updateSkillCount();},dialog,toast});
 function updateSkillCount(){$('#home-skills-count').textContent=skills.length?' '+skills.length:'';}
 function templateSkills(){const template=library?.templates.find(t=>t.id===chosen);return structuredClone(template?.custom?template.designSkills||[]:library?.defaultDesignSkills||[]);}
 function selectTemplateSkills(){if(!skillsEdited){skills=templateSkills();updateSkillCount();}}
 function saveSystems(){localStorage.setItem('cosmic-design-systems',JSON.stringify(systems));}
 function preview(p){if(p.kind==='scene')return `<div class="mini-scene">${templateIcon('cube')}</div>`;const {board:b,layers}=p.preview;return `<div class="mini-board" style="background:${b.fill};aspect-ratio:${b.width}/${b.height}">${layers.map(l=>`<span style="left:${l.x/b.width*100}%;top:${l.y/b.height*100}%;width:${l.width/b.width*100}%;height:${l.height/b.height*100}%;background:${l.fill};border-radius:${l.radius*.14}px;color:${l.color};font-family:${fonts[l.fontFamily]||fonts.sans};font-size:${Math.max(2,l.fontSize/b.width*150)}px;${l.type==='button'?'text-align:center':''}">${esc(l.text||'')}</span>`).join('')}</div>`;}
 async function show(){await flush();library=await api('list_projects');if(!skillsInitialized){skills=templateSkills();skillsInitialized=true;updateSkillCount();}document.body.classList.add('home-visible');document.body.classList.remove('presenting','inspector-open');$('#exit-present').hidden=true;render();}
 function updateSelection(){
  document.querySelectorAll('[data-template]').forEach(b=>{const active=b.dataset.template===chosen;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
  $('#chosen-template').textContent=library.templates.find(t=>t.id===chosen)?.name||'Blank canvas';
 }
 function render(){if(!library)return;
  if(!library.templates.some(t=>t.id===chosen))chosen=library.templates[0]?.id||'blank';
  $('#template-grid').innerHTML=library.templates.map(t=>`<article class="template-tile"><button class="template-card" data-template="${esc(t.id)}" aria-pressed="false"><span class="template-check" aria-hidden="true">✓</span><span class="template-art ${esc(t.icon)}">${templateIcon(t.icon)}</span><strong>${esc(t.name)}</strong><small>${esc(t.description)}</small></button><button class="template-more" data-template-menu="${esc(t.id)}" aria-label="Options for ${esc(t.name)} template" aria-expanded="false" aria-haspopup="true">···</button><div class="template-menu" data-menu-for="${esc(t.id)}" hidden><button data-remove-template="${esc(t.id)}">Delete template</button></div></article>`).join('')||'<p class="templates-empty">A fresh canvas is always here. Restore a starting point in Manage templates.</p>';
  document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{chosen=b.dataset.template;selectTemplateSkills();closeMenus();updateSelection();});
  document.querySelectorAll('[data-template-menu]').forEach(b=>b.onclick=()=>{const menu=b.nextElementSibling,opening=menu.hidden;closeMenus();menu.hidden=!opening;b.setAttribute('aria-expanded',String(opening));if(opening)menu.querySelector('button').focus();});
  document.querySelectorAll('[data-remove-template]').forEach(b=>b.onclick=()=>removeTemplate(b.dataset.removeTemplate));updateSelection();
  const system=$('#home-system').value;$('#home-system').innerHTML='<option value="">Template style</option>'+systems.map(s=>`<option value="${esc(s.id)}" ${s.id===system?'selected':''}>${esc(s.name)}</option>`).join('');
  renderList();
 }
 function closeMenus(){document.querySelectorAll('.template-menu').forEach(m=>m.hidden=true);document.querySelectorAll('[data-template-menu]').forEach(b=>b.setAttribute('aria-expanded','false'));}
 async function removeTemplate(id){try{const t=library.templates.find(t=>t.id===id);library=await api('delete_template',{id});render();if($('#template-manager'))renderManager();toast(`${t?.name||'Template'} deleted.`,{label:'Undo',onClick:()=>restoreTemplate(id)});}catch(e){toast(e.message);}}
 async function restoreTemplate(id){try{library=await api('delete_template',{id,restore:true});render();if($('#template-manager'))renderManager();toast('Template restored.');}catch(e){toast(e.message);}}
 function renderManager(){const list=(items,deleted)=>items.map(t=>`<div class="manage-template-row"><span class="manage-template-icon">${templateIcon(t.icon)}</span><div><strong>${esc(t.name)}</strong><small>${t.custom?'Your template':'Built-in template'}</small></div><button data-manage-${deleted?'restore':'delete'}="${esc(t.id)}">${deleted?'Restore':'Delete'}</button></div>`).join('');
  $('#template-manager').innerHTML=`<p>Choose the starting points you want to keep. Your projects stay saved.</p><h3>In your library</h3>${list(library.templates,false)||'<p class="muted">No templates in the library.</p>'}<h3>Deleted templates</h3>${list(library.deletedTemplates||[],true)||'<p class="muted">Nothing deleted.</p>'}`;
  document.querySelectorAll('[data-manage-delete]').forEach(b=>b.onclick=()=>removeTemplate(b.dataset.manageDelete));document.querySelectorAll('[data-manage-restore]').forEach(b=>b.onclick=()=>restoreTemplate(b.dataset.manageRestore));
 }
 $('#manage-templates').onclick=()=>{closeMenus();dialog('Manage templates','<div id="template-manager"></div>');renderManager();};
 document.addEventListener('click',e=>{if(!e.target.closest('.template-tile'))closeMenus();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=document.querySelector('[data-template-menu][aria-expanded="true"]');closeMenus();open?.focus();}});
 attachPromptHints($('#home-prompt'),$('#home-prompt-field'));
 function renderList(){const q=$('#project-search').value.toLowerCase();$('#new-design-system').hidden=filter!=='systems';document.querySelectorAll('[data-library-tab]').forEach(b=>b.classList.toggle('active',b.dataset.libraryTab===filter));
  if(filter==='systems'){
   $('#project-list').innerHTML=systems.filter(s=>s.name.toLowerCase().includes(q)).map(s=>`<article class="saved-system"><div class="system-swatches">${[s.background,s.ink,s.accent].map(c=>`<span style="background:${c}"></span>`).join('')}</div><div><strong>${esc(s.name)}</strong><small>${esc(s.font)} · palette and typography</small></div><button data-edit-system="${esc(s.id)}">Edit</button><button data-delete-system="${esc(s.id)}" aria-label="Delete ${esc(s.name)}">×</button></article>`).join('')||'<p class="library-empty">Save colors and a typeface to reuse across your projects.</p>';
   document.querySelectorAll('[data-edit-system]').forEach(b=>b.onclick=()=>editSystem(b.dataset.editSystem));document.querySelectorAll('[data-delete-system]').forEach(b=>b.onclick=()=>{systems=systems.filter(s=>s.id!==b.dataset.deleteSystem);saveSystems();render();});return;
  }
  if(filter==='templates'){
   $('#project-list').innerHTML=library.templates.filter(t=>t.name.toLowerCase().includes(q)).map(t=>`<article class="saved-template"><span class="saved-template-icon">${templateIcon(t.icon)}</span><div><strong>${esc(t.name)}</strong><small>${t.custom?'Your template':'Built-in starter'}</small></div><button data-use-template="${esc(t.id)}">Use template</button><button data-delete-template="${esc(t.id)}" aria-label="Delete ${esc(t.name)} template">Delete</button></article>`).join('');
   document.querySelectorAll('[data-use-template]').forEach(b=>b.onclick=()=>{chosen=b.dataset.useTemplate;selectTemplateSkills();create(false);});document.querySelectorAll('[data-delete-template]').forEach(b=>b.onclick=()=>removeTemplate(b.dataset.deleteTemplate));return;
  }
  const items=library.projects.filter(p=>p.deleted===(filter==='trash')&&p.name.toLowerCase().includes(q));
  $('#project-list').innerHTML=items.length?items.map(p=>`<article class="saved-project"><button class="project-open" data-open-project="${p.id}" ${p.deleted?'disabled':''}><div class="project-thumb">${preview(p)}</div><div class="project-summary"><strong>${esc(p.name)}</strong><small>${p.kind==='scene'?p.objectCount+' objects · Three.js':p.boardCount+' pages · '+p.layerCount+' elements'}</small></div></button><time>${new Date(p.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time>${p.deleted?`<button data-restore="${p.id}">Restore</button>`:`<button class="project-menu" data-project-menu="${p.id}" aria-label="Options for ${esc(p.name)}">···</button>`}</article>`).join(''):`<div class="library-empty">${filter==='trash'?'Trash is empty. Deleted projects can be restored here.':q?'No projects match your search.':'Your next idea starts above. Choose a template to begin.'}</div>`;
  document.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=async()=>{try{await openDocument((await api('open_project',{id:b.dataset.openProject})).document);}catch(e){toast(e.message);}});document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{library=await api('trash_project',{id:b.dataset.restore,deleted:false});render();toast('Project restored.');});document.querySelectorAll('[data-project-menu]').forEach(b=>b.onclick=()=>projectMenu(b.dataset.projectMenu));
 }
 function projectMenu(id){const p=library.projects.find(p=>p.id===id);dialog('Project options',`<label class="prop-field">Name<input id="rename-value" value="${esc(p.name)}" maxlength="200"></label><div class="dialog-buttons"><button id="rename-project">Rename</button><button id="save-project-template">Save as template</button><button id="duplicate-project">Duplicate project</button><button id="trash-project" class="danger">Move to Trash</button></div>`);
  $('#rename-project').onclick=async()=>{await api('rename_project',{id,name:$('#rename-value').value});$('#dialog').close();await show();};$('#save-project-template').onclick=async()=>{library=await api('save_template',{id,name:$('#rename-value').value});$('#dialog').close();render();toast('Template saved.');};$('#duplicate-project').onclick=async()=>{const d=(await api('read_design',{projectId:id,includeImages:true})).document;const copy=await api('create_project',{document:d,name:d.name+' copy'});$('#dialog').close();await openDocument(copy.document);};$('#trash-project').onclick=async()=>{library=await api('trash_project',{id});$('#dialog').close();render();toast('Moved to Trash. You can restore it anytime.');};
 }
 async function create(withAI){const prompt=$('#home-prompt').value.trim();$('#home-create').disabled=true;$('#home-start').disabled=true;try{const system=systems.find(s=>s.id===$('#home-system').value);const brief=prompt+(system?`\nDesign system: ${system.name}. Background ${system.background}, text ${system.ink}, accent ${system.accent}, ${system.font} typography.`:'');const result=await api('create_project',{templateId:chosen,brief,designSkills:skills,name:prompt?prompt.split('\n')[0].slice(0,80):undefined});await openDocument(result.document);
  skills=[];skillsInitialized=false;skillsEdited=false;updateSkillCount();
  if(system&&getDoc().kind==='canvas'){const d=getDoc();commit([...d.boards.map(b=>({type:'patch-board',id:b.id,patch:{fill:system.background}})),...d.layers.map(l=>({type:'patch-layer',id:l.id,patch:{color:system.ink,...(l.type==='text'?{fontFamily:system.font}:{}),...(l.type==='button'?{fill:system.accent,color:system.background}:{})}}))]);}
  if(files.length){await uploadFiles(files,true);files=[];renderAttachments();}const links=$('#home-links').value.split('\n').map(v=>v.trim()).filter(Boolean);for(const url of links){if(/^https?:\/\/\S+$/.test(url))commit([{type:'add-reference',url,notes:'Project starting reference'}]);}await flush();$('#prompt').value=brief;$('#model').value=$('#home-model').value;$('#model').onchange();$('#effort').value=$('#home-effort').value;if(withAI&&prompt)await generate();else toast('Project created. Start editing or describe what you want.');
 }catch(e){toast(e.message);}finally{$('#home-create').disabled=false;$('#home-start').disabled=false;}}
 function renderAttachments(){$('#home-attachments').innerHTML=files.map((f,i)=>`<span class="attachment-chip">▧ ${esc(f.name)}<button data-remove-attachment="${i}" aria-label="Remove ${esc(f.name)}">×</button></span>`).join('');document.querySelectorAll('[data-remove-attachment]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.removeAttachment),1);renderAttachments();});}
 function editSystem(id){const s=systems.find(s=>s.id===id)||{id:crypto.randomUUID(),name:'New design system',background:'#f6f4ef',ink:'#253c32',accent:'#799484',font:'sans'};dialog('Design system',`<label class="prop-field">Name<input id="system-name" value="${esc(s.name)}"></label><div class="system-color-fields">${['background','ink','accent'].map(k=>`<label class="prop-field">${k}<input id="system-${k}" type="color" value="${s[k]}"></label>`).join('')}</div><label class="prop-field">Typeface<select id="system-font">${['sans','serif','mono'].map(f=>`<option ${f===s.font?'selected':''}>${f}</option>`).join('')}</select></label><button id="save-system" class="wide primary">Save design system</button>`);$('#save-system').onclick=()=>{const next={id:s.id,name:$('#system-name').value.trim()||'Design system',background:$('#system-background').value,ink:$('#system-ink').value,accent:$('#system-accent').value,font:$('#system-font').value};systems=systems.filter(v=>v.id!==s.id).concat(next);saveSystems();$('#dialog').close();render();};}
 $('#home-button').onclick=()=>show().catch(e=>toast(e.message));$('#home-create').onclick=()=>create(true);$('#home-start').onclick=()=>create(false);$('#project-search').oninput=renderList;document.querySelectorAll('[data-library-tab]').forEach(b=>b.onclick=()=>{filter=b.dataset.libraryTab;renderList();});$('#new-design-system').onclick=()=>editSystem();$('#home-upload').onclick=()=>$('#home-file-input').click();$('#home-file-input').onchange=e=>{files.push(...e.target.files);renderAttachments();e.target.value='';};$('#home-add-links').onclick=()=>{$('#home-links').hidden=!$('#home-links').hidden;if(!$('#home-links').hidden)$('#home-links').focus();};
 const composer=$('#home-composer');composer.addEventListener('dragover',e=>e.preventDefault());composer.addEventListener('drop',async e=>{e.preventDefault();const incoming=[...e.dataTransfer.files],guides=incoming.filter(f=>/\.(md|txt)$/i.test(f.name));try{if(guides.length){skills=await readSkillFiles(guides,skills);skillsEdited=true;updateSkillCount();toast('Design skills attached.');}files.push(...incoming.filter(f=>/^image\//.test(f.type)));renderAttachments();}catch(err){toast(err.message);}});composer.addEventListener('paste',e=>{const incoming=[...e.clipboardData.items].filter(i=>i.kind==='file').map(i=>i.getAsFile());if(incoming.length){e.preventDefault();files.push(...incoming);renderAttachments();}});
 $('#home-model').innerHTML=$('#model').innerHTML;$('#home-effort').innerHTML=$('#effort').innerHTML;$('#home-model').onchange=()=>{const previous=$('#model').value;$('#model').value=$('#home-model').value;$('#model').onchange();$('#home-effort').innerHTML=$('#effort').innerHTML;$('#home-effort').value=$('#effort').value;$('#model').value=previous;$('#model').onchange();};
 return{show,create,render};
}
