// This function is self-contained so exported HTML runs this exact component code.
export function createPrototypeRuntime({onNavigate,onNotice}={}){
 let doc={layers:[],boards:[]},projectKey,interactive=false,updates=[],inputs=[],noticeTimer;const values=new Map(),defaults=new Map(),pressed=new Set();
 const options=l=>(l.text||'Option one\nOption two').split('\n').filter(Boolean);
 function numeric(l,value){const min=l.min??0,max=l.max??100,step=l.step||1;const n=Number(value);return Number(Math.max(min,Math.min(max,min+Math.round(((Number.isFinite(n)?n:min)-min)/step)*step)).toFixed(6));}
 function initial(l){if(['toggle','checkbox','accordion'].includes(l.type))return !!l.checked;if(['slider','progress'].includes(l.type))return numeric(l,l.value===''||l.value===undefined?50:l.value);if(['select','tabs'].includes(l.type)){const list=options(l);return list.includes(String(l.value))?String(l.value):list[0]||'';}return l.value??'';}
 function layer(id){return doc.layers.find(l=>l.id===id);}
 function read(id,seen=new Set()){const l=layer(id);if(!l||seen.has(id))return '';seen.add(id);if(l.valueSource)return read(l.valueSource,seen);return interactive&&values.has(id)?values.get(id):initial(l);}
 function refresh(){for(const update of updates)update();}
 function set(id,value){const l=layer(id);if(!l)return;if(['slider','progress'].includes(l.type))value=numeric(l,value);else if(['toggle','checkbox','accordion'].includes(l.type))value=!!value;else if(['select','tabs'].includes(l.type)&&!options(l).includes(String(value)))return;values.set(id,value);refresh();}
 function reset(){values.clear();pressed.clear();refresh();for(const {node} of inputs){node.classList.remove('proto-invalid');node.removeAttribute('aria-invalid');}}
 function notice(message){if(onNotice){onNotice(message);return;}let el=document.getElementById('cosmic-prototype-notice');if(!el){el=document.createElement('div');el.id='cosmic-prototype-notice';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;el.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove('show'),3500);}
 function navigate(id){if(!id||!doc.boards.some(b=>b.id===id)){notice('Choose a destination page for this control.');return;}onNavigate?.(id);}
 function activate(l){if(l.disabled)return;const action=l.action||'auto',target=layer(l.actionTarget);if(action==='none')return;if(action==='navigate'||action==='auto'&&l.targetBoard){navigate(l.targetBoard);return;}
  if(action==='reset'){reset();notice('Preview reset.');return;}
  if(action==='submit'){for(const {node,boardId} of inputs){if(boardId===l.boardId&&!node.disabled&&!node.reportValidity())return;}notice(l.actionMessage||'Form checked in this preview.');return;}
  if(['toggle','increment','decrement'].includes(action)){if(!target){notice('Choose a target component for this action.');return;}const previous=read(target.id);if(action==='toggle')set(target.id,!previous);else set(target.id,(Number(previous)||0)+(action==='increment'?1:-1)*(target.step||1));return;}
  if(action==='message'){notice(l.actionMessage||`${l.text||l.name} clicked.`);return;}
  pressed.has(l.id)?pressed.delete(l.id):pressed.add(l.id);refresh();
 }
 function beginFrame(next,live){const key=next.projectId||next.name;if(key!==projectKey){values.clear();defaults.clear();pressed.clear();projectKey=key;}doc=next;interactive=live;updates=[];inputs=[];
  const ids=new Set(doc.layers.map(l=>l.id));for(const id of values.keys())if(!ids.has(id))values.delete(id);
  for(const l of doc.layers){const signature=JSON.stringify([l.type,l.value,l.checked,l.min,l.max,l.step,['tabs','select'].includes(l.type)?l.text:'']);if(defaults.has(l.id)&&defaults.get(l.id)!==signature)values.delete(l.id);defaults.set(l.id,signature);}
 }
 function mount(l,host,asset){
  const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  const root=node('div','proto-root proto-'+l.type);root.dataset.live=String(interactive);root.dataset.disabled=String(!!l.disabled);root.style.setProperty('--proto-accent',l.color);root.style.setProperty('--proto-fill',l.fill);root.style.setProperty('--proto-hover',l.hoverColor||l.fill);root.style.setProperty('--proto-control-size',Math.min(18,Math.max(12,l.fontSize))+'px');
  root.dataset.hover=l.hoverEffect||'auto';if(l.hoverColor)root.classList.add('proto-custom-hover');if(l.tooltip)root.title=l.tooltip;
  const sync=fn=>{updates.push(fn);fn();};
  const formatted=()=>{const v=read(l.id);return typeof v==='boolean'?(v?'On':'Off'):String(v);};
  const label=()=>l.text.includes('{{value}}')?l.text.replaceAll('{{value}}',formatted()):l.valueSource?formatted()+(l.suffix||''):l.text;
  const mark=(control)=>{control.setAttribute('aria-label',l.name);control.disabled=!!l.disabled;control.tabIndex=interactive?0:-1;control.name=l.id;return control;};
  const icon=()=>{
   const paths={folder:'M3 7h7l2 2h9v11H3z M3 7V4h7l2 3',film:'M4 3h16v18H4z M8 3v18M16 3v18M4 7h4M4 12h4M4 17h4M16 7h4M16 12h4M16 17h4',play:'m8 5 11 7-11 7z',pause:'M8 5v14M16 5v14',plus:'M12 5v14M5 12h14',search:'M21 21l-6-6 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',list:'M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1','arrow-right':'M4 12h16m-6-6 6 6-6 6','chevron-right':'m9 5 7 7-7 7','chevron-down':'m5 9 7 7 7-7',upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6',download:'M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M12 6v7l4 2',check:'m4 12 5 5L20 6',close:'m5 5 14 14M19 5 5 19',more:'M4 12h1M11 12h1M18 12h1',link:'m9 15 6-6M8 17l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M13 16a4 4 0 0 0 6 0l4-4a4 4 0 0 0-6-6l-1 1',volume:'M3 9h4l5-5v16l-5-5H3zM16 8q5 4 0 8M19 4q9 8 0 16',image:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M15 7h1',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2'};
   if(!paths[l.icon])return null;
   const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),path=document.createElementNS('http://www.w3.org/2000/svg','path');
   svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.7');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');svg.classList.add('proto-icon');path.setAttribute('d',paths[l.icon]);svg.append(path);return svg;
  };
  if(l.filterSource)sync(()=>{const q=interactive?String(read(l.filterSource)).trim().toLowerCase():'';const container=host.parentElement||root;container.style.visibility=q&&!String(l.filterText||l.name).toLowerCase().includes(q)?'hidden':'';});
  let actionElement=null;
  if(l.type==='text'){sync(()=>{root.textContent=label();});}
  else if(l.type==='image'){if(asset){const img=node('img');img.src=asset.data;img.alt=asset.name;img.style.objectFit=l.fit;root.append(img);}else{root.classList.add('proto-image-empty');root.textContent='Drop an image';}}
  else if(l.type==='shape'){const mark=icon();if(mark){root.classList.add('proto-icon-only');root.append(mark);}}
  else if(l.type==='button'){const button=mark(node('button','proto-button')),glyph=icon(),copy=node('span');button.type='button';if(glyph)button.append(glyph);button.append(copy);root.append(button);actionElement=button;sync(()=>{copy.textContent=label();if((l.action==='auto'||!l.action)&&!l.targetBoard){button.setAttribute('aria-pressed',String(pressed.has(l.id)));}else button.removeAttribute('aria-pressed');});}
  else if(['input','textarea'].includes(l.type)){const input=mark(node(l.type==='textarea'?'textarea':'input','proto-input'));if(l.type==='input')input.type=l.inputType||'text';input.placeholder=l.text;input.required=!!l.required;input.autocomplete='off';input.oninput=()=>{set(l.id,input.value);input.classList.remove('proto-invalid');input.removeAttribute('aria-invalid');};input.oninvalid=()=>{input.classList.add('proto-invalid');input.setAttribute('aria-invalid','true');};sync(()=>{const next=String(read(l.id));if(input.value!==next)input.value=next;});root.append(input);inputs.push({node:input,boardId:l.boardId});}
  else if(l.type==='slider'){const range=mark(node('input','proto-range')),output=node('output','proto-value');range.type='range';range.min=l.min??0;range.max=l.max??100;range.step=l.step||1;range.id='proto-input-'+l.id;output.htmlFor=range.id;range.oninput=()=>set(l.id,range.value);sync(()=>{const v=numeric(l,read(l.id));range.value=String(v);output.value=v+(l.suffix||'');range.setAttribute('aria-valuetext',output.value);root.style.setProperty('--proto-percent',(v-(l.min??0))/((l.max??100)-(l.min??0))*100+'%');});root.append(range,output);}
  else if(['toggle','checkbox'].includes(l.type)){const labelEl=node('label','proto-check-label'),input=mark(node('input','proto-check'));input.type='checkbox';input.required=!!l.required;if(l.type==='toggle')input.setAttribute('role','switch');const visual=node('span','proto-check-visual');visual.setAttribute('aria-hidden','true');if(l.type==='toggle')visual.append(node('span','proto-thumb'));else visual.textContent='✓';input.onchange=()=>{set(l.id,input.checked);input.removeAttribute('aria-invalid');};input.oninvalid=()=>input.setAttribute('aria-invalid','true');sync(()=>{input.checked=!!read(l.id);root.dataset.checked=String(input.checked);});labelEl.append(input,visual);if(l.text)labelEl.append(node('span','proto-check-text',l.text));root.append(labelEl);inputs.push({node:input,boardId:l.boardId});}
  else if(l.type==='select'){const select=mark(node('select','proto-select'));select.required=!!l.required;for(const t of options(l)){const option=node('option','',t);option.value=t;select.append(option);}select.onchange=()=>set(l.id,select.value);sync(()=>{select.value=String(read(l.id));});root.append(select);inputs.push({node:select,boardId:l.boardId});}
  else if(l.type==='tabs'){root.setAttribute('role','tablist');root.setAttribute('aria-label',l.name);const list=options(l);const tabs=list.map((text,i)=>{const tab=mark(node('button','proto-tab',text));tab.type='button';tab.setAttribute('role','tab');tab.setAttribute('aria-label',text);tab.onclick=()=>{set(l.id,text);if(l.optionTargets?.[i])navigate(l.optionTargets[i]);};tab.onkeydown=e=>{const delta={ArrowRight:1,ArrowLeft:-1,Home:-i,End:list.length-1-i}[e.key];if(delta!==undefined){e.preventDefault();const next=tabs[(i+delta+list.length)%list.length];next.focus();next.click();}};root.append(tab);return tab;});sync(()=>tabs.forEach((tab,i)=>{const selected=list[i]===read(l.id);tab.setAttribute('aria-selected',String(selected));tab.tabIndex=interactive&&selected?0:-1;}));}
  else if(l.type==='accordion'){const [title,...body]=l.text.split('\n'),button=mark(node('button','proto-accordion-trigger')),copy=node('span','',title||l.name),chevron=node('span','proto-chevron','⌄'),panel=node('div','proto-accordion-panel'),inner=node('div','proto-accordion-inner',body.join('\n'));button.type='button';chevron.setAttribute('aria-hidden','true');button.append(copy,chevron);panel.id='proto-panel-'+l.id;button.setAttribute('aria-controls',panel.id);panel.append(inner);button.onclick=()=>set(l.id,!read(l.id));sync(()=>{const open=!!read(l.id);button.setAttribute('aria-expanded',String(open));panel.setAttribute('aria-hidden',String(!open));root.dataset.expanded=String(open);});root.append(button,panel);}
  else if(l.type==='progress'){const track=node('div','proto-progress-track'),bar=node('div','proto-progress-fill'),out=node('output','proto-value');track.append(bar);root.append(track,out);root.setAttribute('role','progressbar');root.setAttribute('aria-label',l.name);sync(()=>{const v=numeric(l,read(l.id)),percent=(v-(l.min??0))/((l.max??100)-(l.min??0))*100;bar.style.width=percent+'%';out.value=v+(l.suffix||'');root.setAttribute('aria-valuemin',String(l.min??0));root.setAttribute('aria-valuemax',String(l.max??100));root.setAttribute('aria-valuenow',String(v));});}
  if(!actionElement&&['text','image','shape'].includes(l.type)&&(l.targetBoard||!['auto','none',undefined].includes(l.action))){actionElement=root;root.setAttribute('role','button');root.setAttribute('aria-label',l.name);root.tabIndex=interactive?0:-1;root.classList.add('proto-clickable');root.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(l);}};}
  if(actionElement)actionElement.onclick=()=>{if(interactive)activate(l);};
  if(!interactive){root.style.pointerEvents='none';root.inert=true;}
  if(l.disabled){root.querySelectorAll('button,input,textarea,select').forEach(e=>e.disabled=true);if(actionElement===root)root.setAttribute('aria-disabled','true');}
  host.append(root);return root;
 }
 return{beginFrame,mount,read,set,reset,activate,getState:()=>Object.fromEntries(doc.layers.filter(l=>['input','textarea','slider','toggle','checkbox','select','tabs','accordion','progress'].includes(l.type)).map(l=>[l.id,read(l.id)]))};
}

export const prototypeStyles=`
.proto-root{width:100%;height:100%;font:inherit;color:inherit;line-height:inherit;border-radius:inherit;box-sizing:border-box;position:relative;--proto-accent:#386bf2;--proto-control-size:15px}
.proto-icon{width:1.2em;height:1.2em;flex-shrink:0}.proto-icon-only{display:flex;align-items:center;justify-content:center}.proto-icon-only .proto-icon{width:100%;height:100%}.proto-button{gap:8px}.proto-button>span:empty{display:none}
.proto-root *{box-sizing:border-box}.proto-root img{display:block;width:100%;height:100%}.proto-root button,.proto-root input,.proto-root select,.proto-root textarea{font:inherit;color:inherit;letter-spacing:inherit;margin:0;min-width:0;box-shadow:none;accent-color:var(--proto-accent);transition:background-color 180ms ease,border-color 180ms ease,box-shadow 180ms ease,filter 180ms ease,transform 180ms ease}
.proto-root button{cursor:pointer}.proto-root button:disabled,.proto-root input:disabled,.proto-root select:disabled{cursor:not-allowed}.proto-root[data-disabled=true]{opacity:.45}.proto-root [type=range]{cursor:ew-resize}
.proto-root .proto-button{display:flex;align-items:center;justify-content:center;width:100%;height:100%;background:transparent;border:0;border-radius:inherit;padding:0 12px;white-space:pre-wrap;text-align:inherit;line-height:inherit;transform:none}
.proto-root[data-live=true] .proto-button:hover,.proto-root[data-live=true] .proto-accordion-trigger:hover{background:#ffffff18}.proto-root[data-live=true] .proto-button:active{transform:scale(.97);background:#00000014}.proto-root .proto-button[aria-pressed=true]{box-shadow:inset 0 0 0 2px currentColor;background:#ffffff18}
.proto-root[data-live=true] button:focus-visible,.proto-root[data-live=true] input:focus-visible,.proto-root[data-live=true] select:focus-visible,.proto-root[data-live=true] textarea:focus-visible,.proto-root.proto-clickable:focus-visible{outline:2px solid var(--proto-accent);outline-offset:-3px}
.proto-root .proto-input,.proto-root .proto-select{width:100%;height:100%;background:transparent;border:1px solid #8886;border-radius:inherit;padding:9px 12px;font:inherit;line-height:1.4}.proto-root textarea.proto-input{resize:none}.proto-root .proto-input::placeholder{color:inherit;opacity:.5}.proto-root[data-live=true] .proto-input:hover,.proto-root[data-live=true] .proto-select:hover{border-color:currentColor}.proto-root .proto-input:focus,.proto-root .proto-select:focus{border-color:var(--proto-accent)}.proto-root .proto-input.proto-invalid{border:2px solid #dc4444}.proto-root option{background:var(--proto-fill,#fff);color:var(--proto-accent)}
.proto-root.proto-slider,.proto-root.proto-progress{display:flex;align-items:center;gap:12px}.proto-root .proto-range{appearance:none;-webkit-appearance:none;min-width:0;width:100%;flex:1;height:5px;padding:0;border:0;border-radius:4px;background:linear-gradient(to right,var(--proto-accent) var(--proto-percent,50%),#8885 var(--proto-percent,50%));outline:none}
.proto-root .proto-range::-webkit-slider-thumb{appearance:none;-webkit-appearance:none;width:16px;height:16px;background:var(--proto-accent);border:2px solid #fff;border-radius:50%;box-shadow:0 1px 4px #0003;transition:box-shadow 180ms ease,transform 180ms ease}.proto-root[data-live=true] .proto-range:hover::-webkit-slider-thumb{box-shadow:0 0 0 5px #8882;transform:scale(1.12)}.proto-root .proto-range::-moz-range-thumb{width:13px;height:13px;background:var(--proto-accent);border:2px solid #fff;border-radius:50%}
.proto-root .proto-value{font-family:inherit;line-height:1.3;font-size:var(--proto-control-size);font-variant-numeric:tabular-nums;white-space:nowrap;min-width:2.5ch;text-align:right;flex-shrink:0;color:inherit}
.proto-root .proto-check-label{position:relative;display:flex;align-items:center;gap:10px;height:100%;width:100%;cursor:pointer;font:inherit;color:inherit}.proto-root .proto-check{position:absolute;inset:0;width:100%;height:100%;margin:0;opacity:0;cursor:pointer;z-index:2}.proto-root .proto-check-visual{display:flex;align-items:center;justify-content:center;flex-shrink:0;width:20px;height:20px;border:1px solid #8888;background:#8882;border-radius:5px;color:transparent;transition:background 180ms ease,border-color 180ms ease,box-shadow 180ms ease}.proto-root .proto-check:checked+.proto-check-visual{background:var(--proto-accent);border-color:var(--proto-accent);color:#fff}.proto-root .proto-check:focus-visible+.proto-check-visual{outline:2px solid var(--proto-accent);outline-offset:3px}
.proto-root.proto-toggle .proto-check-visual{width:40px;height:24px;border:0;border-radius:20px;background:#8885;justify-content:flex-start;padding:3px}.proto-root.proto-toggle .proto-thumb{display:block;background:#fff;width:18px;height:18px;border-radius:50%;box-shadow:0 1px 3px #0003;transition:transform 200ms cubic-bezier(.2,.8,.2,1)}.proto-root.proto-toggle .proto-check:checked+.proto-check-visual .proto-thumb{transform:translateX(16px)}.proto-root[data-live=true] .proto-check-label:hover .proto-check-visual{box-shadow:0 0 0 4px #8882}.proto-root .proto-check-text{font-size:var(--proto-control-size)}
.proto-root.proto-tabs{display:flex;gap:3px;padding:4px;background:#8881}.proto-root .proto-tab{border:0;border-radius:inherit;flex:1;background:transparent;padding:5px 8px;font:inherit;color:inherit;white-space:nowrap}.proto-root .proto-tab[aria-selected=true]{background:#8882;box-shadow:0 1px 5px #0001}.proto-root[data-live=true] .proto-tab:hover{background:#8882}
.proto-root.proto-accordion{display:flex;flex-direction:column;overflow:hidden;border:1px solid #8885}.proto-root .proto-accordion-trigger{display:flex;align-items:center;justify-content:space-between;text-align:left;border:0;background:transparent;color:inherit;font:inherit;flex-shrink:0;min-height:48px;padding:12px 15px;gap:10px;border-radius:inherit}.proto-root .proto-chevron{transition:transform 200ms ease}.proto-root[data-expanded=true] .proto-chevron{transform:rotate(180deg)}.proto-root .proto-accordion-panel{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows 220ms ease,opacity 180ms ease}.proto-root[data-expanded=true] .proto-accordion-panel{grid-template-rows:1fr;opacity:1}.proto-root .proto-accordion-inner{overflow:hidden;min-height:0;line-height:1.6;font-size:var(--proto-control-size);padding:0 15px}.proto-root[data-expanded=true] .proto-accordion-inner{padding-bottom:15px}
.proto-root .proto-progress-track{flex:1;min-width:0;height:8px;border-radius:8px;background:#8883;overflow:hidden}.proto-root .proto-progress-fill{height:100%;border-radius:inherit;background:var(--proto-accent);transition:width 160ms ease}.proto-image-empty{display:flex;align-items:center;justify-content:center;border:1px dashed #a0a5ae;font:14px Arial;color:#727984}
.proto-root[data-live=true][data-hover=lift]:hover{transform:translateY(-3px)}.proto-root[data-live=true][data-hover=zoom]:hover{transform:scale(1.025)}.proto-root[data-live=true][data-hover=glow]:hover{box-shadow:0 0 0 3px #8883,0 8px 22px #0001}.proto-root[data-live=true].proto-custom-hover:hover{background:var(--proto-hover)}.proto-root{transition:transform 200ms ease,box-shadow 200ms ease,background-color 180ms ease}.proto-root.proto-clickable{cursor:pointer}.proto-root[data-live=true].proto-clickable[data-hover=auto]:hover{filter:brightness(1.08)}.proto-root[data-live=true][data-hover=none]:hover,.proto-root[data-live=true][data-hover=none] button:hover{transform:none;filter:none;box-shadow:none;background:transparent}
#cosmic-prototype-notice{position:fixed;bottom:26px;left:50%;transform:translate(-50%,20px);max-width:min(500px,85vw);padding:13px 19px;border-radius:12px;background:#20242beF;color:#fff;font:14px/1.5 Arial;box-shadow:0 8px 30px #0003;z-index:60;opacity:0;pointer-events:none;transition:opacity 180ms ease,transform 180ms ease}#cosmic-prototype-notice.show{opacity:1;transform:translate(-50%,0)}
@media(prefers-reduced-motion:reduce){.proto-root,.proto-root *{transition:none!important;animation:none!important}.proto-root:hover{transform:none!important}}
`;
