import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {objectSchema,escapeHtml as esc} from './model.mjs';
export function createSceneEditor({container,commit,getDoc,toast,download}){
 const $=s=>document.querySelector(s);let renderer,world,camera,orbit,transform,group,grid,box,activeId=null,last='',enabled=false,dragging=false,down=null,animation=false,failed=false;
 const shapes={box:()=>new THREE.BoxGeometry(1,1,1),sphere:()=>new THREE.SphereGeometry(.75,40,24),torus:()=>new THREE.TorusGeometry(.8,.23,24,72),cylinder:()=>new THREE.CylinderGeometry(.7,.7,1,48),cone:()=>new THREE.ConeGeometry(.75,1.5,40),plane:()=>new THREE.PlaneGeometry(2,2)};
 function init(){if(renderer||failed)return;try{
  world=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.01,1000);camera.position.set(6,4.2,7);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive Three.js scene');
  orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.2,0);orbit.enableDamping=true;orbit.update();
  world.add(new THREE.HemisphereLight('#ffffff','#69718d',3));const key=new THREE.DirectionalLight('#ffe9d2',4);key.position.set(4,6,3);world.add(key);const rim=new THREE.DirectionalLight('#c8d5ff',3);rim.position.set(-4,3,-4);world.add(rim);
  group=new THREE.Group();world.add(group);grid=new THREE.GridHelper(20,40,'#677084','#313844');world.add(grid);box=new THREE.BoxHelper(new THREE.Mesh(),0xb7c8ff);box.visible=false;world.add(box);
  transform=new TransformControls(camera,renderer.domElement);world.add(transform.getHelper());transform.addEventListener('dragging-changed',e=>{dragging=e.value;orbit.enabled=!e.value;});transform.addEventListener('objectChange',()=>{if(transform.object)box.setFromObject(transform.object);});transform.addEventListener('mouseUp',()=>{const m=transform.object;if(!m)return;commit([{type:'patch-object',id:m.userData.id,patch:{position:m.position.toArray().map(round),rotation:[m.rotation.x,m.rotation.y,m.rotation.z].map(v=>round(THREE.MathUtils.radToDeg(v))),scale:m.scale.toArray().map(v=>Math.max(.01,round(v)))}}]);});
  const ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,axis:transform.axis};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||down.axis||transform.axis||dragging||Math.hypot(e.clientX-down.x,e.clientY-down.y)>4)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children.filter(o=>o.visible))[0];select(hit?.object.userData.id||null);});
  new ResizeObserver(resize).observe(container);renderer.setAnimationLoop(()=>{if(!enabled)return;orbit.autoRotate=animation;orbit.autoRotateSpeed=1.2;orbit.update();renderer.render(world,camera);});
 }catch(e){failed=true;container.innerHTML='<p class="scene-unavailable">3D rendering could not start. Enable WebGL in your browser, then reload. Your scene is still saved.</p>';toast('WebGL unavailable: '+e.message);}}
 function round(v){return Math.round(v*1000)/1000;}
 function resize(){if(!renderer||!container.clientWidth)return;renderer.setSize(container.clientWidth,container.clientHeight,false);camera.aspect=container.clientWidth/Math.max(1,container.clientHeight);camera.updateProjectionMatrix();}
 function clear(){if(!group)return;transform.detach();for(const m of [...group.children]){group.remove(m);m.geometry.dispose();m.material.dispose();}}
 function update(scene){enabled=true;container.hidden=false;init();if(failed)return;const signature=JSON.stringify(scene);if(signature!==last&&!dragging){clear();world.background=new THREE.Color(scene.background);grid.visible=scene.grid;for(const o of scene.objects){const mesh=new THREE.Mesh(shapes[o.geometry](),new THREE.MeshStandardMaterial({color:o.color,metalness:o.metalness,roughness:o.roughness,side:THREE.DoubleSide}));mesh.name=o.name;mesh.userData.id=o.id;mesh.position.fromArray(o.position);mesh.rotation.set(...o.rotation.map(THREE.MathUtils.degToRad));mesh.scale.fromArray(o.scale);mesh.visible=o.visible;group.add(mesh);}last=signature;}if(!scene.objects.some(o=>o.id===activeId))activeId=null;attach();renderPanels();resize();}
 function attach(){if(!transform)return;const mesh=group.children.find(m=>m.userData.id===activeId);if(mesh?.visible){transform.attach(mesh);box.setFromObject(mesh);box.visible=true;}else{transform.detach();box.visible=false;}}
 function select(id){activeId=id;attach();renderPanels();$('#selection-note').textContent=id?getDoc().scene.objects.find(o=>o.id===id)?.name+' selected':'Whole scene';}
 function renderPanels(){const scene=getDoc().scene,o=scene.objects.find(o=>o.id===activeId);$('#boards').innerHTML='<div class="scene-tree-title">Scene collection <span>Three.js</span></div>';$('#layer-count').textContent=scene.objects.length;$('#layers').innerHTML=scene.objects.map(o=>`<button class="scene-object ${o.id===activeId?'active':''}" data-object="${esc(o.id)}"><span>◇</span>${esc(o.name)}<small>${esc(o.geometry)}</small></button>`).join('')||'<p class="muted">Add an object to begin.</p>';document.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>select(b.dataset.object));$('#inspector-type').textContent=o?'Object':'Scene';
  const field=(label,html)=>`<label class="prop-field prop-full">${label}${html}</label>`;
  let html=`<section class="prop-section"><h3>Scene</h3>${field('Background',`<input id="scene-background" type="color" value="${scene.background}">`)}<label class="scene-check"><input id="scene-grid" type="checkbox" ${scene.grid?'checked':''}> Show grid</label><button id="scene-reset" class="wide">Reset camera</button><button id="scene-spin" class="wide">${animation?'Stop':'Start'} turntable</button></section>`;
  if(o){html+=`<section class="prop-section"><h3>Selected object</h3>${field('Name',`<input data-object-prop="name" value="${esc(o.name)}">`)}${field('Geometry',`<select data-object-prop="geometry">${Object.keys(shapes).map(v=>`<option ${v===o.geometry?'selected':''}>${v}</option>`).join('')}</select>`)}<label class="scene-check"><input data-object-prop="visible" type="checkbox" ${o.visible?'checked':''}> Visible</label></section>`;for(const key of ['position','rotation','scale'])html+=`<section class="prop-section"><h3>${key==='rotation'?'Rotation · degrees':key}</h3><div class="scene-vector">${o[key].map((v,i)=>`<label class="prop-field"><span data-scene-scrub="${key}:${i}" title="Drag to scrub">${'XYZ'[i]}</span><input type="number" step="${key==='rotation'?1:.1}" data-vector="${key}:${i}" value="${v}"></label>`).join('')}</div></section>`;
  html+=`<section class="prop-section"><h3>Material</h3>${field('Color',`<input type="color" data-object-prop="color" value="${o.color}">`)}${['metalness','roughness'].map(k=>field(k,`<input type="range" min="0" max="1" step=".01" data-object-prop="${k}" value="${o[k]}">`)).join('')}</section>`;}
  $('#properties').innerHTML=html;$('#scene-background').onchange=e=>commit([{type:'patch-scene',patch:{background:e.target.value}}]);$('#scene-grid').onchange=e=>commit([{type:'patch-scene',patch:{grid:e.target.checked}}]);$('#scene-reset').onclick=reset;$('#scene-spin').onclick=()=>{animation=!animation;renderPanels();};
  document.querySelectorAll('[data-object-prop]').forEach(el=>el.onchange=()=>commit([{type:'patch-object',id:activeId,patch:{[el.dataset.objectProp]:el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value}}]));
  document.querySelectorAll('[data-vector]').forEach(el=>el.onchange=()=>{const [k,i]=el.dataset.vector.split(':'),v=[...o[k]];v[i]=Number(el.value);commit([{type:'patch-object',id:activeId,patch:{[k]:v}}]);});
  document.querySelectorAll('[data-scene-scrub]').forEach(el=>el.onpointerdown=e=>{e.preventDefault();const [k,i]=el.dataset.sceneScrub.split(':'),start=e.clientX,original=[...o[k]],input=el.nextElementSibling;let value=original[i];const move=ev=>{value=round(original[i]+(ev.clientX-start)*(k==='rotation'?1:.02));if(k==='scale')value=Math.max(.01,value);input.value=value;};const end=()=>{document.removeEventListener('pointermove',move);const v=[...original];v[i]=value;commit([{type:'patch-object',id:activeId,patch:{[k]:v}}]);};document.addEventListener('pointermove',move);document.addEventListener('pointerup',end,{once:true});});
 }
 function reset(){if(!camera)return;camera.position.set(6,4.2,7);orbit.target.set(0,1.2,0);orbit.update();}
 function add(geometry){const o=objectSchema.parse({id:crypto.randomUUID(),name:geometry[0].toUpperCase()+geometry.slice(1),geometry,position:[0,1,0]});activeId=o.id;commit([{type:'add-object',object:o}]);}
 function remove(){if(activeId)commit([{type:'delete-object',id:activeId}]);}
 function duplicate(){const o=getDoc().scene.objects.find(o=>o.id===activeId);if(o){const copy={...o,id:crypto.randomUUID(),name:o.name+' copy',position:[o.position[0]+1,o.position[1],o.position[2]]};activeId=copy.id;commit([{type:'add-object',object:copy}]);}}
 async function exportGlb(){if(!group)throw Error('3D renderer unavailable');const result=await new GLTFExporter().parseAsync(group,{binary:true});download(result,'cosmic-scene.glb','model/gltf-binary');}
 return{update,add,remove,duplicate,exportGlb,select,get selectedIds(){return activeId?[activeId]:[];},get interacting(){return dragging;},setTransform(mode){transform?.setMode(mode);},reset,hide(){enabled=false;container.hidden=true;transform?.detach();},screenshot(){if(renderer)downloadData(renderer.domElement.toDataURL('image/png'));}};
 function downloadData(data){const a=document.createElement('a');a.href=data;a.download='cosmic-scene.png';a.click();}
}
