import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemo,applyOperations,validateDocument,exportHtml,layerSchema,layerStyle} from '../src/model.mjs';
import {parseRunOperations} from '../src/design-operations.mjs';
import {buildSessionParams} from '../src/codex-session.mjs';

test('richer styling stays editable, validates safe values, and survives HTML export',()=>{
 const d=createDemo();d.layers[0]=layerSchema.parse({...d.layers[0],fontFamily:'display',letterSpacing:-.5,lineHeight:1.3,borderColor:'#121212',borderWidth:1,shadow:'raised',gradientTo:'#eeeeee',gradientAngle:120,icon:'film'});
 const styles=layerStyle(d.layers[0]);assert.match(styles.background,/linear-gradient\(120deg/);assert.equal(styles.letterSpacing,'-0.5px');assert.equal(styles.border,'1px solid #121212');assert.match(styles.boxShadow,/24px/);assert.ok(exportHtml(d).includes('linear-gradient(120deg'));
 assert.throws(()=>layerSchema.parse({...d.layers[0],gradientTo:'url(https://evil.example)'}));assert.throws(()=>layerSchema.parse({...d.layers[0],icon:'<script>'}));assert.throws(()=>layerSchema.parse({...d.layers[0],borderWidth:-1}));
});
test('new text layers default to transparent without changing explicit backgrounds',()=>{const l={id:'heading',boardId:'desktop',type:'text',name:'Heading',x:10,y:10,width:400,height:80};assert.equal(layerSchema.parse(l).fill,'transparent');assert.equal(layerSchema.parse({...l,fill:'#ffffff'}).fill,'#ffffff');assert.equal(layerSchema.parse({...l,type:'shape'}).fill,'#ffffff');});
test('observed model operation aliases normalize to validated editor operations',()=>{assert.deepEqual(parseRunOperations('[{"op":"patch-object","id":"sculpture","patch":{"roughness":0.3}}]'),[{type:'patch-object',id:'sculpture',patch:{roughness:.3}}]);assert.throws(()=>parseRunOperations('[{"type":"patch-object","op":"delete-object"}]'),/Ambiguous/);assert.throws(()=>parseRunOperations('[{"op":"run-shell"}]'),/unsupported/);});
test('batch edits are atomic on validation failure',()=>{const original=createDemo();assert.throws(()=>applyOperations(original,[{type:'patch-layer',id:'wordmark',patch:{text:'Changed'}},{type:'patch-layer',id:'wordmark',patch:{width:-50}}]));assert.equal(original.layers[0].text,'still.');});
test('new pages, controls, references and comments survive round trip',()=>{const original=createDemo();const next=applyOperations(original,[{type:'add-board',board:{id:'mobile',name:'Mobile',width:390,height:844,fill:'#ffffff'}},{type:'add-layer',layer:layerSchema.parse({id:'input',boardId:'mobile',name:'Email',type:'input',x:20,y:40,width:320,height:42})},{type:'add-reference',url:'https://example.com',notes:'Navigation'},{type:'add-review',text:'Increase spacing',layerId:'input'}]);const restored=validateDocument(JSON.parse(JSON.stringify(next)));assert.equal(restored.boards.length,2);assert.equal(restored.layers.at(-1).type,'input');assert.equal(restored.references[0].notes,'Navigation');assert.equal(restored.reviews[0].layerId,'input');});
test('rejects unsafe assets, references, unknown boards and duplicate IDs',()=>{const d=createDemo();assert.throws(()=>applyOperations(d,[{type:'add-reference',url:'javascript:alert(1)'}]));assert.throws(()=>applyOperations(d,[{type:'add-layer',layer:{...d.layers[0],id:'bad',boardId:'missing'}}]));assert.throws(()=>applyOperations(d,[{type:'add-layer',layer:d.layers[0]}]));assert.throws(()=>applyOperations(d,[{type:'add-asset',asset:{id:'../../escape',name:'bad',data:'data:image/png;base64,YQ==',width:1,height:1,role:'asset'}}]));});
test('HTML export escapes hostile text and keeps native controls',()=>{const d=createDemo();d.name='<script>alert(1)</script>';d.layers[0].text='</div><script>alert(2)</script>';d.layers.push(layerSchema.parse({id:'slider',boardId:'desktop',type:'slider',name:'Size',x:10,y:600,width:250,height:30}));const html=exportHtml(d);assert.ok(!html.includes('<script>alert('));assert.ok(html.includes('&lt;script&gt;alert(1)'));assert.ok(html.includes('type="range"'));assert.ok(html.includes('data-target="board-desktop"'));});
test('model and effort choices reach an isolated streaming session',()=>{const p=buildSessionParams({cwd:'C:/design',model:'gpt-6-astra',effort:'xhigh',prompt:'Create a page',images:['ref.png']});assert.equal(p.thread.model,'gpt-6-astra');assert.equal(p.turn.effort,'xhigh');assert.equal(p.thread.ephemeral,true);assert.deepEqual(p.turn.environments,[]);assert.equal(p.turn.sandboxPolicy.type,'readOnly');assert.equal(p.turn.sandboxPolicy.networkAccess,false);assert.equal(p.thread.config['features.shell_tool'],false);assert.equal(p.turn.input[1].path,'ref.png');assert.throws(()=>buildSessionParams({model:'gpt-5.5',effort:'ultra'}));assert.throws(()=>buildSessionParams({model:'foo & dangerous',effort:'high'}));});
